name: Update versions

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run get-versions script
        run: |
          chmod +x get-versions.sh
          ./get-versions.sh

      - name: Check for changes
        id: changes
        run: |
          if [ "$(git status --porcelain versions.json)" ]; then
            echo "versions.json changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "versions.json unchanged"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.changes.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: updated hibiscus server version"
